# Project: stack
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = mi.o
LINKOBJ  = mi.o
LIBS     = -L"D:/dev-c++/Dev-Cpp/MinGW64/lib" -L"D:/dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/dev-c++/Dev-Cpp/MinGW64/include" -I"D:/dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/dev-c++/Dev-Cpp/MinGW64/include" -I"D:/dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = stack.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

mi.o: mi.cpp
	$(CPP) -c mi.cpp -o mi.o $(CXXFLAGS)
